### ISSUE TITLE
Hi! I'm really thanks for your  BundleFusionUbuntuKinectV2, But When I tested TUM dataset! it cannont add depth frame.

### ISSUE THREAD

**Issue by ghost** [AlDCheng/kinect_ar#1]
I've change the Parameters, I don't know how to figure it out! So I hope you can give me some suggestions! (Sorry for my terrible English!)

**Comment by AlDCheng** [comment]
Hey thanks for looking at my repos. I've moved that repo into a branch of the original Ubuntu port of BundleFusion here: https://github.com/AlDCheng/BundleFusion_Ubuntu_Pangolin (Original: https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin).

My fork only adds a Kinect V2 wrapper around the base code that allows for real-time functionality with it. I also haven't really tested it since I started a new job. **If you are just trying to run the TUM dataset, I would recommend cloning from the original repo (the one from FangGet linked above), and redirecting any questions there.**

Hope that helps!

[P.S.] I think you posted in the wrong repo of mine? This current repo you've posted to is just some code dump from my Master thesis work.

**Comment by ghost** [comment]
> Hey thanks for looking at my repos. I've moved that repo into a branch of the original Ubuntu port of BundleFusion here: https://github.com/AlDCheng/BundleFusion_Ubuntu_Pangolin (Original: https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin).
> 
> My fork only adds a Kinect V2 wrapper around the base code that allows for real-time functionality with it. I also haven't really tested it since I started a new job. **If you are just trying to run the TUM dataset, I would recommend cloning from the original repo (the one from FangGet linked above), and redirecting any questions there.**
> 
> Hope that helps!
> 
> [P.S.] I think you posted in the wrong repo of mine? This current repo you've posted to is just some code dump from my Master thesis work.

Hey! Thanks for your reply! I post my question here because there is no ISSUE interface in your project-/BundleFusion_Ubuntu_PangolinKinectv2. I'll post my issue in the original project.

And sorry for replying you so late!
